# Generated by Django 4.2.1 on 2024-05-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallax_image', models.ImageField(upload_to='events/')),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=255)),
                ('countdown_time', models.DateTimeField()),
                ('event_image', models.ImageField(upload_to='events/')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
