# Generated by Django 4.2.1 on 2024-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featuredevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('thumbnail_image', models.ImageField(upload_to='thumbnails/')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
