# Generated by Django 4.2.1 on 2024-06-09 17:51

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
